import os

SQL_STREAMS_TABLE_NAME_KEY = "VENTY_SQL_STREAMS_TABLE_NAME"
SQL_STREAMS_TABLE_NAME_DEFAULT = "venty_streams"
SQL_STREAMS_TABLE_NAME = os.environ.get(
    SQL_STREAMS_TABLE_NAME_KEY, SQL_STREAMS_TABLE_NAME_DEFAULT
)
SQL_RECORDED_EVENTS_TABLE_NAME_KEY = "VENTY_SQL_RECORDED_EVENTS_TABLE_NAME"
SQL_RECORDED_EVENTS_TABLE_NAME_DEFAULT = "venty_recorded_events"
SQL_RECORDED_EVENTS_TABLE_NAME = os.environ.get(
    SQL_RECORDED_EVENTS_TABLE_NAME_KEY, SQL_RECORDED_EVENTS_TABLE_NAME_DEFAULT
)
